### ISSUE TITLE
Add support for "Instructor Insights" Learning Resource type

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-projects#115]
As a course author, I'd like to be able to tag my course to indicate that it contains "Instructor Insights."

I'd also like to tag individual resources to indicate that they are part of "Instructor Insights" 

#### Acceptance Criteria:

- [ ] add "Instructor Insights" to [the ocw-studio.yml for ocw-course](https://github.com/mitodl/ocw-hugo-projects/blob/aac1ae4faf56767191fcc09157dc406e44ba04a6/ocw-course/ocw-studio.yaml#L295-L296) for courses 
- [ ] add "Instructor Insights" to [the ocw-studio.yml for ocw-course](https://github.com/mitodl/ocw-hugo-projects/blob/aac1ae4faf56767191fcc09157dc406e44ba04a6/ocw-course/ocw-studio.yaml#L83-L84) for resources 

#### Related issues

- import Instructor Insights course tags from legacy courses
- display Instructor Insights on the course home page

**Comment by MAbdurrehman12** [comment]
> I'd also like to tag individual resources to indicate that they are part of "Instructor Insights"

I'm thinking how this is achievable via this PR
