### ISSUE TITLE
Add a field for youtube description

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-projects#156]
As a course author, I'd like to have a way to enter text and have it published to YouTube when my video is published. 

The youtube description has requirements that are different from simple resource descriptions, so it should be a separate field. 

#### Acceptance Criteria:

- [x] Add a field with appropriate help text 
- [x] there shouldn't be any existing data in production intended to go to YouTube, so a migration shouldn't be necessary
- [ ] update the YouTube metadata updating code in ocw-studio to use this new field instead of the resource description

#### Out of Scope

- In the future, we may want to automate the population of this field somehow. 

#### Relates Issues

#152

**Comment by gumaerc** [comment]
I put up https://github.com/mitodl/ocw-hugo-projects/pull/157 to add the new YouTube description field.  After that merges, a follow up PR will need to be made in `ocw-studio` to change the default value of `YT_FIELD_DESCRIPTION` to `video_metadata.youtube_description`.
