### ISSUE TITLE
ocw-course: default value for Draft should be false

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-projects#173]
As a user, it's annoying that I have to explicitly set "Draft" to false for new resources. I don't have to do this for other items, like pages. 

#### Acceptance Criteria:

- [ ] default value for "Draft" should be false

**Comment by ChristopherChudzicki** [comment]
@Wassaf-Shahzad fyi I opened https://github.com/mitodl/ocw-studio/pull/1363 for https://github.com/mitodl/ocw-studio/issues/1343, so now default values will be set when creating gdrive resources. So if that get's merged, it should be enough to specify the default in the site config
