### ISSUE TITLE
Add Resource bundle(TBD) to ocw-course

### ISSUE THREAD

**Issue by Wassaf-Shahzad** [mitodl/ocw-hugo-projects#196]
## Description
Allow course authors to create curated lists of resources , similar to the "courses list" in ocw-www, "resource collections" in ocw-www, and "video galleries" in ocw-course.

## Related Links
Issue Part of following [discussion thread](https://github.com/mitodl/hq/discussions/93)

**Comment by rhysyngsun** [comment]
@Wassaf-Shahzad I forgot to reopen this, but we had to revert this because it broke publishing: https://github.com/mitodl/ocw-hugo-projects/pull/206

**Comment by Wassaf-Shahzad** [comment]
> @Wassaf-Shahzad I forgot to reopen this, but we had to revert this because it broke publishing: #206

@rhysyngsun This PR adds the resource list to the picker https://github.com/mitodl/ocw-studio/pull/1412
and this PR (is merged) adds a check to prevent ocw-studio blowing up if a link exists in config and not in tabs https://github.com/mitodl/ocw-studio/pull/1411

So I think we can revert the revert after the next release of ocw-stuido
