### ISSUE TITLE
Add optional field to describe if a collection is sortable

### ISSUE THREAD

**Issue by Wassaf-Shahzad** [mitodl/ocw-hugo-projects#237]
As per discussion on [post](https://github.com/mitodl/ocw-hugo-projects/issues/183), We need to add sortable collections. As per [comment](https://github.com/mitodl/ocw-hugo-projects/issues/183#issuecomment-1152734173) . We need to add a configuration to determine if a collection is sortable.

#### Linked issue
- This issue is a part of https://github.com/mitodl/ocw-hugo-projects/issues/183

#### Acceptance Criteria:
- [ ] Add a config to determine if a collection is sortable.

**Comment by ChristopherChudzicki** [comment]
@Wassaf-Shahzad I think we can close this now that
- https://github.com/mitodl/ocw-hugo-themes/pull/1053 
- https://github.com/mitodl/ocw-hugo-projects/pull/242

If I'm wrong, re-open!

**Comment by pdpinch** [comment]
@ChristopherChudzicki what about https://github.com/mitodl/ocw-hugo-projects/pull/238 ?
