### ISSUE TITLE
enable relativeUrls: true for all sites

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-hugo-projects#239]
As part of the efforts to consolidate the differences between the online and offline themes in https://github.com/mitodl/ocw-hugo-themes/issues/1013, we should set `relativeUrls: true` in the site configs to tell Hugo to render relative URLs by default. This should only be done when the corresponding changes in `ocw-studio` and ` ocw-hugo-themes` are ready to go as it will be disruptive if deployed before the changes are made to the way the URLs are rendered.

**Comment by pdpinch** [comment]
@gumaerc should this still be done?

**Comment by gumaerc** [comment]
@pdpinch No, as we decided not to pursue consolidating the online and offline themes: https://github.com/mitodl/ocw-hugo-themes/issues/1013#issuecomment-1430279581
