### ISSUE TITLE
add course features

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-hugo-projects#24]
There should be a list of course feature tags in the course site starter that can be set on:
 - Course Metadata
 - Resources

**Comment by pdpinch** [comment]
The controlled vocabulary of course features should be based on the list of tags we developed for ocw-data-parser:

https://github.com/mitodl/ocw-data-parser/blob/2580dcaf52be4e2e0c1098be527bd19cfc8e7288/ocw_data_parser/course_feature_tags.py#L59-L101

Each course feature should have a corresponding resource type. In general, the resource type should be a singular form of the corresponding course feature. For example the course feature "Lecture Videos" should be associated with the resource type "Lecture Video" 

If there are ambiguous cases, let me know so I can review.
