### ISSUE TITLE
Add resource metadata for videos

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-projects#56]
As a course author, I need to be able to add metadata to video resources. I also need to be able to connect video resources I create with videos that have been delivered through google drive (see https://github.com/mitodl/ocw-studio/issues/403) 

#### Acceptance Criteria:

- [ ] Metadata is conditional on the resource file type being Video
- [ ] Decide how to connect resources to processed video: will we use the YouTube ID, a YouTube URL or a relation internal to ocw-studio?
- [ ] Some fields will be populated via the connected video. ~~It would be convenient for this fields to be read-only. If not, they should be hidden.~~

**Comment by Ferdi** [comment]
What are the fields / metadata ?

**Comment by pdpinch** [comment]
Hers's an RFC: https://docs.google.com/document/d/1rAFX8VMaT5EN_1aJqTlEP6SHrBU-5m6zg8ieyKej3fE/edit#

(I was trying to make a PR, but I think an RFC works better)
