### ISSUE TITLE
rename `course_feature_type` to `learningResourceType`

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-projects#58]
As a OCW admin, I'd like to have our metadata fields align, where possible, with widely used metadata schemes. 

To this end, we can rename `course_feature_tags` to match schema.org/LMRI's [learningResourceType](https://schema.org/learningResourceType).

replace https://github.com/mitodl/ocw-hugo-projects/blob/9a10fdc3409b5ab4d3b29db4e0bcea917ec3ab9b/ocw-course/ocw-studio.yaml#L200-L201

with:
```
          - label: "Learning Resource Type"
            name: "learningResourceType"
```

### related issues

- - Since this is schema.org markup, it should be expressed in course hugo theme to maximize SEO

**Comment by pdpinch** [comment]
Question: is it necessary or desirable to match the camel-case used in schema.org? Or should we retain our underscore-separated naming?

**Comment by gumaerc** [comment]
@pdpinch Since the `name` property ultimately ends up being the key in the data template, I'd prefer if we could use underscores to keep everything consistent.  Personally, I find underscore separated naming easier to read and prefer it to camel case but that's just my opinion.  Either way, I think we should stay consistent here.

**Comment by pdpinch** [comment]
Ok, as long as you don't think it's too confusing to (eventually) have a hugo theme that maps course metadata `learning_restource_type` to `learningResourceType` in JSON-LD.

**Comment by gumaerc** [comment]
In my mind, underscore separated is better for JSON / YAML keys and Python variables / constants but in Javascript camel case is better for variables and constants.  I could just be subtlety influenced by our formatting rules though...
