### ISSUE TITLE
add PR template

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-hugo-projects#83]
This repo should have a PR template with some checkboxes to ensure some tasks are completed:

 - [ ] Changes tested with `ocw-studio` by adding the starter to your local instance
 - [ ] Changes manually tested by:
   - [ ] creating a site with that starter
   - [ ] adding content using the field(s) you have changed
   - [ ] saving / publishing the site and verifying the output

**Comment by pdpinch** [comment]
no longer necessary. this repo inherits PR templates from the organization
